version: "3.8"

services:
  api:
    image: msithaba/credit-card-api:latest
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  ui:
    image: msithaba/credit-card-ui:latest
    ports:
      - "8080:80"

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - /home/ubuntu/volumes/uptime_kuma_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  uptime_kuma_data: