name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: [self-hosted, linux, x64, credit-card]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install API Dependencies
        working-directory: ./credit-card-api
        run: npm install

      - name: Test
        working-directory: ./credit-card-api
        run: npm run test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push API Image
        run: |
          cd credit-card-api
          docker build -t msithaba/credit-card-api:latest .
          docker push msithaba/credit-card-api:latest

      - name: Install UI Dependencies
        working-directory: ./credit-card-ui
        run: npm install

      - name: Build UI
        working-directory: ./credit-card-ui
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.API_URL }}

      - name: Build and Push UI Image
        run: |
          cd credit-card-ui
          docker build -t msithaba/credit-card-ui:latest .
          docker push msithaba/credit-card-ui:latest

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, linux, x64, credit-card]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: deploy using docker compose
        run: |
          docker compose up -d 
          docker image prune -f
          docker container prune -f